### PR TITLE
:lipstick: :ambulance: Fixed logo overlapping nav bar on tablet

### PR DESCRIPTION
**Pull request by svpernova09**
See screenshot: Top version is the fix contained here, below is the current version in tablet size.

screenshot 2016-10-15 21 18 22

### CODE REVIEW

**Comment by funkatron** [comment]
So, thank you so much for this!

I think the fundamental problem here is that the nav toolbar is wrapping. That's not something I want happening. We need to fix that. It doesn't wrap on any media query I use on Chrome desktop, but it's possible rendering differences are causing it. It would help a lot if I knew what device and browser it was happening on.

**Comment by svpernova09** [comment]
I saw the logo issue on Chrome, Safari, and Firefox. Also verified the fix on all 3 as well

**Comment by funkatron** [comment]
Weird! What OS?

**Comment by svpernova09** [comment]
OS X can check my windows machine as well and will update

-
Joe Ferguson

**Comment by funkatron** [comment]
I don't see this on OS X. I'll post something

**Comment by funkatron** [comment]
Check out this gigantic video https://www.dropbox.com/s/50e0ab9144cezif/Capto_Capture%202016-10-17_11-28-43_AM.mov?dl=0

**Pull request closed without merging**
